trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ARM_CLIENT_ID: $(ARM_CLIENT)
  ARM_CLIENT_SECRET: $(ARM_CLIENTT)
  ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION)
  ARM_TENANT_ID: $(ARM_TENANT)
  backendResourceGroup: 'tf-webapp-rg'
  backendStorageAccount: 'tf1storageacc'
  backendContainer: 'terraform-state'
  backendKey: 'dev.terraform.tfstate'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Free Trial(77845c72-6418-4086-8008-06c3bcb08b0f)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Azure CLI is authenticated"
      az account show

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- script: |
    terraform init \
      -backend-config="resource_group_name=$(backendResourceGroup)" \
      -backend-config="storage_account_name=$(backendStorageAccount)" \
      -backend-config="container_name=$(backendContainer)" \
      -backend-config="key=$(backendKey)"
  displayName: 'Terraform Init'
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT)
    ARM_CLIENT_SECRET: $(ARM_CLIENTT)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION)
    ARM_TENANT_ID: $(ARM_TENANT)

- script: terraform plan
  displayName: 'Terraform Plan'
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT)
    ARM_CLIENT_SECRET: $(ARM_CLIENTT)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION)
    ARM_TENANT_ID: $(ARM_TENANT)

- script: terraform apply -auto-approve
  displayName: 'Terraform Apply'
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT)
    ARM_CLIENT_SECRET: $(ARM_CLIENTT)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION)
    ARM_TENANT_ID: $(ARM_TENANT)
